version: "3"

services:
  custom_exporter:
    image: llybood/custom_exporter:latest
    container_name: custom_exporter
    volumes:
      - ./conf/config.yaml:/app/custom_exporter/conf/config.yaml
      - ./script:/app/custom_exporter/script
    ports:
      - "9111:9111"
    restart: always
    #network_mode: host
